name: Build and Push Docker Image
run-name: ${{ github.actor }} ran Build and Push

on:
  push:
    branches:
      - feature-test
   
env:
  AWS_REGION: us-east-1                              # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: mentorhub           ## set this to your Amazon ECR repository name
                                          
jobs:
   check-links:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push Docker image to public ECR
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: public.ecr.aws/k4m2e4q5/mentorhub:latest


