name: Build and Push Docker Image
run-name: ${{ github.actor }} ran Build and Push

on:
  push:
    branches:
      - feature-test
   
env:
  AWS_REGION: us-east-1                              ## set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: mentorhub           ## set this to your Amazon ECR repository name
                                          
jobs:
   check-links:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - 
        name: Docker Login to ECR (if needed)
        run: docker login --username AWS --password public.ecr.aws/k4m2e4q5
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}


      - 
        name: Set AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}" >> $GITHUB_ENV
      - 
        name: Login to ECR 
        uses: aws-actions/amazon-ecr-login@v1
        
      - 
        name: Build and push Docker image to public ECR
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: public.ecr.aws/k4m2e4q5/mentorhub:latest
          registry: public.ecr.aws


